### PR TITLE
fix(openchallenges): improve query parameter management using location service

### LINKED ISSUE #2154: [Bug] Reset scrolling position when navigating to another page (Take 2)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

The initial solution proposed in #1972 introduced a side effect. The changes made in #1972 have been undone in #2153.

See:

- #1972 
- #2153

### Expected behavior

_No response_

### Anything else?

_No response_

### Commit ID

_No response_

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rrchai**
- fixes #2154 

## Changelogs

- Replace `router.navigate` with `location.replaceState()` to update url params without initiating navigation or scroll restoration
- Trigger API call by updating query once params are updated
- Refactor search pages' `*_component.ts` files
  - challenge-search: 608 -> 397 lines
  - org-search: 332 -> 316 lines (could reduce more by moving codes of generating orgCard to a global service, but save for a future pr)

### CODE REVIEW

File: libs/openchallenges/challenge-search/src/lib/challenge-search-filters.ts [hunk 1]
```diff
@@ -1,88 +1,163 @@
...
+  },
+];
+
+export const challengeOrganizationsFilter: Filter[] = [];
+
+export const challengeOrganizersFilter: Filter[] = [];
+
+export const challengeSortFilter: Filter[] = [
+  {
+    value: 'relevance',
```
Comment (tschaffter) [inline libs/openchallenges/challenge-search/src/lib/challenge-search-filters.ts:152]: Would that work if we replace the string value by its enum value? This approach is more robust.

```suggestion
    value: ChallengeSort.Relevance,
```

**Review by tschaffter — COMMENTED** [review]
The code refactoring looks great!

I'm having a CORS issue on my end that prevent the challenges from loading in the search page. I will check if this issue is also in `main`.

**Comment by tschaffter** [comment]
@rrchai Filtering orgs by "Contribution Role" does not filter the results.

**Review by tschaffter — CHANGES_REQUESTED** [review]
See comment above.

**Review by tschaffter — APPROVED** [review]
