### PR TITLE
fix: Use default avatar if image service is down

### LINKED ISSUE #1659: [Bug] Org cards are not shown if the request to the get the image URL fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

The org cards are not shown on the org search page when their requests to get their logo URL - not the logo itself - fails. I bumped into this case when working on routing the requests to Thumbor via the Apex.

image

### Expected behavior

An org card should still show if the request to get its logo URL fails. In this case, we should show the initial avatar as backend.

### Anything else?

_No response_

### Commit ID

_No response_

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rrchai**
- fixes #1659 

When the image url is not successfully retrieved from image service, the organization card is not loaded at all. To avoid this behavior, this pr is to return default empty string as avatarUrl if the image service is failed.

## Preview

Screen Shot 2023-08-03 at 5 54 14 PM

### CODE REVIEW

**Comment by rrchai** [comment]
some image sizes are not expected to change, convert to draft now

File: libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts [hunk 1]
```diff
@@ -539,17 +539,20 @@ export class ChallengeSearchComponent
...
         aspectRatio: ImageAspectRatio._11,
-      } as ImageQuery);
-    } else {
-      return of(undefined);
-    }
+      } as ImageQuery)
+      .pipe(
+        catchError(() => {
+          console.error(
+            'Unable to get the image url. Please check the logs of image service'
```
Comment (tschaffter) [inline libs/openchallenges/challenge-search/src/lib/challenge-search.component.ts:552]:
```suggestion
            'Unable to get the image url. Please check the logs of the image service.'
```

File: libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.ts [hunk 2]
```diff
@@ -67,24 +67,27 @@ export class ChallengeContributorsComponent implements OnInit {
...
         aspectRatio: ImageAspectRatio._11,
-      } as ImageQuery);
-    } else {
-      return of(undefined);
-    }
+      } as ImageQuery)
+      .pipe(
+        catchError(() => {
+          console.error(
+            'Unable to get the image url. Please check the logs of image service'
```
Comment (tschaffter) [inline libs/openchallenges/challenge/src/lib/challenge-contributors/challenge-contributors.component.ts:80]:
```suggestion
            'Unable to get the image url. Please check the logs of the image service.'
```

File: libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.ts [hunk 3]
```diff
@@ -64,24 +64,27 @@ export class ChallengeHostListComponent implements OnInit {
...
         aspectRatio: ImageAspectRatio._11,
-      } as ImageQuery);
-    } else {
-      return of(undefined);
-    }
+      } as ImageQuery)
+      .pipe(
+        catchError(() => {
+          console.error(
+            'Unable to get the image url. Please check the logs of image service'
```
Comment (tschaffter) [inline libs/openchallenges/home/src/lib/challenge-host-list/challenge-host-list.component.ts:77]:
```suggestion
            'Unable to get the image url. Please check the logs of the image service.'
```

File: libs/openchallenges/org-profile/src/lib/org-profile.component.ts [hunk 4]
```diff
@@ -102,17 +102,20 @@ export class OrgProfileComponent implements OnInit {
...
         aspectRatio: ImageAspectRatio._11,
-      } as ImageQuery);
-    } else {
-      return of(undefined);
-    }
+      } as ImageQuery)
+      .pipe(
+        catchError(() => {
+          console.error(
+            'Unable to get the image url. Please check the logs of image service'
```
Comment (tschaffter) [inline libs/openchallenges/org-profile/src/lib/org-profile.component.ts:115]:
```suggestion
            'Unable to get the image url. Please check the logs of the image service.'
```

**Review by tschaffter — APPROVED** [review]
I made one minor suggestion, otherwise LGTM.
