### PR TITLE
fix(openchallenges): refactor tab switching to preserve scroll position on profile pages

### LINKED ISSUE #2310: [Bug] Challenge & org pages jump to the top when selecting a section ⭐
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

Challenge & org pages jump to the top when selecting a section

### Expected behavior

The scrolling position should not be reset when selecting a section.

### Anything else?

We should be able to fix this bug using `Location` as we do on the search pages.

### Commit ID

7ae8482caa921c479f38b5cc0f871baf5334d2e4

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rrchai**
- fixes #2310 

## Changelog

- Update tab switching on profile pages to avoid navigations, which will fix
  1. the scrolling position jumps back to top after switching tabs
  2. the challenge slug disappeared from the URL after switching tabs

  reset-scroll

- Ensure URL parameters sync with active tab 

  i.e. Typing `/org/dream?tab=members` will go to 'member' section

  org-member

### CODE REVIEW

File: libs/openchallenges/org-profile/src/lib/org-profile.component.ts [hunk 1]
```diff
@@ -74,11 +71,9 @@ export class OrgProfileComponent implements OnInit {
   organization$!: Observable<Organization>;
   organizationAvatar$!: Observable<Avatar>;
   loggedIn = true;
-  // organizationAvatar!: Avatar;
   tabs = ORG_PROFILE_TABS;
-  tabKeys: string[] = Object.keys(this.tabs);
   activeTab!: Tab;
-  private subscriptions: Subscription[] = [];
+  private subscriptions = new Subscription();
```
Comment (tschaffter) [inline libs/openchallenges/org-profile/src/lib/org-profile.component.ts:76]: Should be singular

```suggestion
  private subscriptions = new Subscription();
```

**Review by tschaffter — APPROVED** [review]
LGTM! Only one small comment
